# Generated by Django 5.1.1 on 2024-09-07 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_problem_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 9, 7), verbose_name='День рождения'),
        ),
    ]
