# Generated by Django 5.1.1 on 2024-09-10 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_problem_user_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='object_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.objectofwork', verbose_name='Объект АСУТП'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.problemstatus', verbose_name='Выберите статус задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.problemtype', verbose_name='Выберите тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sector', verbose_name='Сектор сотрудника'),
        ),
    ]
