# Generated by Django 4.2.13 on 2024-09-17 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_problem_object_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 9, 17), verbose_name='День рождения'),
        ),
    ]
