# Generated by Django 5.1.1 on 2024-09-25 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 9, 25), verbose_name='День рождения'),
        ),
    ]
