# Generated by Django 4.2.14 on 2024-09-27 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 9, 27), verbose_name='День рождения'),
        ),
    ]
