# Generated by Django 4.2.14 on 2024-10-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user_date_joined_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
