# Generated by Django 4.2.14 on 2024-10-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_sector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectofwork',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
