# Generated by Django 4.2.14 on 2024-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_objectofwork_id_alter_problemstatus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatus',
            name='color',
            field=models.CharField(default='gray.900', max_length=200, verbose_name='Цвет'),
        ),
    ]
