# Generated by Django 4.2.14 on 2024-10-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_problemstatus_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
