# Generated by Django 5.1.1 on 2024-10-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Прикреплённые файлы'),
        ),
    ]
