# Generated by Django 5.1.1 on 2024-10-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_photourl_user_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название файла')),
                ('upload', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Прикреплённые файлы')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='files',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='problems', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='problem',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file', verbose_name='Вложения'),
        ),
    ]
