# Generated by Django 5.1.1 on 2024-10-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_file_remove_user_files_alter_profile_photourl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['id'], 'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='problem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.problem', verbose_name='Вложения'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('problem', 'id')},
        ),
    ]
