# Generated by Django 5.1.1 on 2024-10-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_file_options_remove_problem_files_file_problem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='problem',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file', verbose_name='Вложения'),
        ),
        migrations.RemoveField(
            model_name='file',
            name='problem',
        ),
    ]
