# Generated by Django 5.1.1 on 2024-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_file_options_alter_file_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='files',
        ),
        migrations.AddField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='main.file', verbose_name='Вложения'),
        ),
    ]
