# Generated by Django 5.1.1 on 2024-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_problem_files_problem_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.file', verbose_name='Вложения'),
        ),
    ]
