# Generated by Django 5.1.1 on 2024-10-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_problem_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='name',
        ),
    ]
