# Generated by Django 5.1.1 on 2024-10-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_problem_files_file_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.file', verbose_name='Вложения'),
        ),
    ]
