# Generated by Django 5.1.1 on 2024-10-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_problem_files_problem_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='files',
        ),
        migrations.AddField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.file', verbose_name='Вложения'),
        ),
    ]
