# Generated by Django 5.1.1 on 2024-10-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='files',
        ),
        migrations.AddField(
            model_name='problem',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Прикреплённый файл'),
        ),
    ]
