# Generated by Django 5.1.1 on 2024-10-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_problem_files_problem_file_alter_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file', verbose_name='Вложения'),
        ),
    ]
