# Generated by Django 5.1.1 on 2024-10-29 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_folder_alter_file_id_alter_objectofwork_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.folder', verbose_name='Папка'),
        ),
    ]
