# Generated by Django 5.1.1 on 2024-10-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_journal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='file',
        ),
        migrations.AlterField(
            model_name='problem',
            name='object_of_work',
            field=models.CharField(default='', max_length=150, verbose_name='Объект АСУТП'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(default='', max_length=150, verbose_name='Введите категорию задачи'),
        ),
        migrations.AddField(
            model_name='problem',
            name='file',
            field=models.ManyToManyField(to='main.file', verbose_name='Вложения'),
        ),
    ]
