# Generated by Django 5.1.1 on 2024-11-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_problem_profile_problem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='Номер телефона'),
        ),
    ]
